### ISSUE TITLE
Citation Permission for Paper

### ISSUE THREAD

**Issue by ramamimu** [PhilipMay/stsb-multi-mt#7]
Hi Philip.

I'd like to put your work to my paper since i use MTEB and your STS Benchmark to measure performance some of Sentence Transformer Models from Huggingface. 

Do you have any paper that i can cite with?

**Comment by PhilipMay** [comment]
Hi, I'm glad you can use my data set. Unfortunately, I don't have a paper on it. Maybe you just cite the repository here on GitHub and me as the author?

**Comment by ramamimu** [comment]
Sure, will do. thanks for your confirmation.
